### ISSUE TITLE
Error retrieving local EPG

### ISSUE THREAD

**Issue by babsonnexus** [jgomez177/plex-for-channels#5]
Hey, I'm quite suddenly seeing this error:

```
2024-11-06 17:47:24 Initialize XML File
2024-11-06 17:47:24 Run channels to load self.channel_list
2024-11-06 17:47:24 New token for local generated at 2024-11-06 22:47.24 +0000
2024-11-06 17:47:33 Day One Initialization of EPG data
2024-11-06 17:47:33 Retrieving local EPG data for 2024-11-06 through 2024-11-06
2024-11-06 17:47:54 Continuing to retrive local EPG data....Elapsed time: 20.97 seconds. 150 Channels parsed
2024-11-06 17:47:23 Traceback (most recent call last):
2024-11-06 17:47:23   File "/app/pywsgi.py", line 271, in <module>
2024-11-06 17:47:23     error = providers[provider].create_xml_file(code)
2024-11-06 17:47:23             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-06 17:47:23   File "/app/plex.py", line 571, in create_xml_file
2024-11-06 17:47:23     error_code = self.update_epg(country_code)
2024-11-06 17:47:23                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-06 17:47:23   File "/app/plex.py", line 444, in update_epg
2024-11-06 17:47:23     error = self.read_epg_from_api(start_datetime, start_datetime, 0, id_values, country_code)
2024-11-06 17:47:23             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-06 17:47:23   File "/app/plex.py", line 373, in read_epg_from_api
2024-11-06 17:47:23     resp_metadata.update({"Metadata": resp["MediaContainer"]["Metadata"],
2024-11-06 17:47:23                                       ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
2024-11-06 17:47:23 KeyError: 'Metadata'
2024-11-06 17:48:06 Traceback (most recent call last):
2024-11-06 17:48:06   File "/app/pywsgi.py", line 271, in <module>
2024-11-06 17:48:06     error = providers[provider].create_xml_file(code)
2024-11-06 17:48:06             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-06 17:48:06   File "/app/plex.py", line 571, in create_xml_file
2024-11-06 17:48:06     error_code = self.update_epg(country_code)
2024-11-06 17:48:06                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-06 17:48:06   File "/app/plex.py", line 444, in update_epg
2024-11-06 17:48:06     error = self.read_epg_from_api(start_datetime, start_datetime, 0, id_values, country_code)
2024-11-06 17:48:06             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-06 17:48:06   File "/app/plex.py", line 373, in read_epg_from_api
2024-11-06 17:48:06     resp_metadata.update({"Metadata": resp["MediaContainer"]["Metadata"],
2024-11-06 17:48:06                                       ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
2024-11-06 17:48:06 KeyError: 'Metadata'
```

Rebuilt the container and got the same result. It basically keeps looping doing this.

**Comment by stewartcampbell** [comment]
I believe this is an issue with the API. Saw it 20 minutes ago, but now working again.

I've added logging to my dev version to try catch exactly what is going on.

Will report back if I see it again.

**Comment by babsonnexus** [comment]
> I've added logging to my dev version to try catch exactly what is going on.

@stewartcampbell, I built an image off your `feature/add-all-channels-links` branch and created a container from that. Here's what I immediately saw:

```
2024-11-07 16:48:23 Initialize XML File
2024-11-07 16:48:23 Run channels to load self.channel_list
2024-11-07 16:48:24 New token for local generated at 2024-11-07 21:48.23 +0000
2024-11-07 16:48:34 Day One Initialization of EPG data
2024-11-07 16:48:34 Retrieving local EPG data for 2024-11-07 through 2024-11-07
2024-11-07 16:48:37 Error accessing response data. Response keys: dict_keys(['MediaContainer'])
2024-11-07 16:48:37 Failed to access EPG data: 'Metadata'
2024-11-07 16:48:37 ⇨ http server started on [::]:7777
```

So I at least got to start and the m3u's are happy, but no XML file, obviously.

**Comment by jgomez177** [comment]
Updated code for case when EPG data is blank for a channel
